name: pytest

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        uses: mamba-org/setup-micromamba@v1
        with:
          generate-run-shell: true
          environment-file: tests/envs/pytest.yml
          environment-name: pybio
          
      - run: |
          pytest --version
          pytest
        shell: micromamba-shell {0}
